name: sonarr3-pipeline

on:
  - push

env:
    TAG: 3.0.6.1265

jobs:
  build:
    name: App and Container Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t sonarr3 .
       
    - name: Create tar for trivy
      run:  |
          docker save -o sonarr3.tar sonarr3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        input: sonarr3.tar
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: HIGH,CRITICAL

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Tag docker images
      run:  |
          docker tag sonarr3 ${{ secrets.DOCKER_USERNAME }}/sonarr3:${TAG}
          docker tag sonarr3 ${{ secrets.DOCKER_USERNAME }}/sonarr3:latest
        
    - name: Push docker images
      run:  |
          docker push ${{ secrets.DOCKER_USERNAME }}/sonarr3:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/sonarr3:latest
